girtel/Net2Plan

src/main/java/com/net2plan/gui/tools/GUINetworkDesign.java
The color of the node are the same as the one from the link.
Fixed issue #12
=> The nodes that a route transverses are now highlighted.

src/main/java/com/net2plan/libraries/WDMUtils.java
The fix is currently not tested, however it has been changed to what it was previously commented.
=> Fixed the bug on WDMUtils as reported by Ciril

src/main/java/com/net2plan/gui/utils/ParameterValueDescriptionPanel.java
- Added a new command: #file# which brings up a file chooser who gives the parameter the path of the selected file.
- Added a new command: #files# which does the same as the last one but with multiple files.
=> Added new cell types on the algorithm window

.gitignore, README.md, pom.xml, sh.exe.stackdump
- Updating git ignore.
- Fixed spelling issues on the read me.
- Removing a .dump strayed file.
- Updating POM to version 0.4.3
=> Correcting a few mistakes

src/main/java/com/net2plan/examples/ocnbook/offline/Offline_Example_Algorithm.java, src/main/java/com/net2plan/examples/ocnbook/offline/Offline_dummy.java, src/main/java/com/net2plan/gui/utils/ParameterValueDescriptionPanel.java
-  Added the new tags #file# and #files# which allow the loading of files from a file chooser.
- The cell renderer gives a "..." button which loades the file chooser.
- Writing "#file# abcd" will use "abcd" as the default value of the parameter.
=> Added new cell tokerns support.

src/main/java/com/net2plan/gui/tools/GUINetworkDesign.java, src/main/java/com/net2plan/gui/utils/windows/WindowController.java
- Algorithm executions have been renamed to Offline algorithms.
- When a pop-up window is closed, it returns as a tab on its original position. Maintining the order of the tabs with each pop-up
=> Updating the control window

pom.xml
- Updated POM to that Javadoc accepts Java 1.8
=> Updated Javadoc generation from java 1.7 to java 1.8

src/main/java/com/net2plan/gui/utils/focusPane/DrawNode.java, src/main/java/com/net2plan/gui/utils/focusPane/FigureDemandSequencePanel.java, src/main/java/com/net2plan/gui/utils/focusPane/FigureLinkSequencePanel.java, src/main/java/com/net2plan/gui/utils/focusPane/FigureMulticastDemandSequencePanel.java, src/main/java/com/net2plan/gui/utils/focusPane/FigureMulticastTreePanel.java, src/main/java/com/net2plan/gui/utils/focusPane/FigureNodeSequencePanel.java, src/main/java/com/net2plan/gui/utils/focusPane/FigureResourcePanel.java, src/main/java/com/net2plan/gui/utils/focusPane/FigureSRGSequencePanel.java, src/main/java/com/net2plan/gui/utils/focusPane/FigureSequencePanel.java, src/main/java/com/net2plan/gui/utils/topologyPane/visualizationControl/PickTimeLineManager.java
Reframes the resources panel so that the text is not cut at the edges.
=> Calculating the correct window size for each focus window element

src/main/java/com/net2plan/gui/tools/GUINetworkDesign.java, src/main/java/com/net2plan/gui/utils/viewEditWindows/WindowController.java
- The same shortcuts that are added to the main window are now added too to the tab windows.
=> Shortcuts can now be used on the extra windows.

pom.xml, src/main/java/com/net2plan/gui/GUINet2Plan.java, src/main/java/com/net2plan/gui/utils/viewEditTopolTables/ITableRowFilter.java, src/main/java/com/net2plan/gui/utils/whatIfAnalysisPane/WhatIfAnalysisPane.java
- The toggle button no longer starts activated.
- The button cannot be focused
- Other small things.
=> Solving a few mistakes with WhatIf

.gitignore, src/main/resources/data/networkTopologies/abilene_N12_E30_withTrafficAndClusters3.n2p, src/main/resources/data/networkTopologies/example6nodes.n2p
Two new topologies which are necessary for the tests have been added.
=> Added new topologies

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/TopologyPanel.java
When decreasing interlayer distance until 0, then, you can't increase it. Now, that's fixed.
=> Bug fixed when decreasing interlayer distance until 0

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/MoveNodePlugin.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/PanGraphPlugin.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/PopupMenuPlugin.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/jung/AddLinkGraphPlugin.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/jung/JUNGCanvas.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/jung/osmSupport/state/OSMJUNGOffState.java, README.md
- Updating the project's readme in order to reflect the new POM.
- The Readme may have some errors, it would be better to read-proof it before accepting the request.
=> Updating the ReadMe

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_node.java
- Added a column to see and edit the current population of a node.
=> Added a new column for showing the population number at the node's table

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_link.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_node.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/VisualizationState.java
- The show-hide column at both the node and link table now work as intended.
=> Solving issue#74: The show/hide cell is now in the correct order.

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_NetworkElement.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_demand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_forwardingRule.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_layer.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_link.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_multicastDemand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_multicastTree.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_node.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_resource.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_route.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_srg.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/VisualizationSnapshot.java
- Solved a problem with the VisualizationSnapshot that did not allow for node creation.
=> Solving issue#78: The aggregation row is no longer editable

Net2Plan-Core/src/main/java/com/net2plan/internal/CommandLineParser.java, Net2Plan-Core/src/test/java/com/net2plan/interfaces/networkDesign/InterLayerPropagationGraphTest.java, Net2Plan-GUI/Net2Plan-GUI-Exec/src/main/java/com/net2plan/gui/utils/SolverCheckPanel.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/GUINetworkDesign.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/GUIWindow.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/offlineExecPane/OfflineExecutionPanel.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/jung/GUILayer.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/GUILayer.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/UndoRedoManager.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/VisualizationSnapshot.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/VisualizationState.java
- It is possible to run algorithms again.
=> Solved the synchronization problem when launching algorithms

Net2Plan-Core/src/main/java/com/net2plan/utils/StringUtils.java, Net2Plan-Core/src/test/java/com/net2plan/utils/StringUtilsTest.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/CellRenderers.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/MultiLayerControlPanel.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/ViewEditTopologyTablesPane.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/multilayerTabs/AdvancedJTable_multiLayerControlTable.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_demand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_forwardingRule.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_layer.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_link.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_multicastDemand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_multicastTree.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_networkElement.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_node.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_resource.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_route.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_srg.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/tableStateFiles/TableStateController.java
- It is now possible to sort the rows of a table with the tag column.
- The tags are now displayed the same way as the attributes.
=> Row sorting with tag column

Net2Plan-GUI/Net2Plan-GUI-Exec/src/main/java/com/net2plan/gui/utils/SolverCheckPanel.java
- Fix a detail where the tester printed the linux libray path under windows.
=> Tester no longer checks linux path under windows

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/GUINetworkDesign.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/PickTimeLineManager.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/VisualizationState.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/test/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/PickTimeLineManagerTest.java
- Simplifyin the class PickTimelineManager.
- Added more exception conditions.
- Added tests to check its behaviour.
=> Remaking the PickTimelineManager

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_node.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/visualizationControl/PickTimeLineManager.java
- Fixed a problem that did not allow for new elements to be added if all the previous elements of the timeline had been removed.
- Added a check when adding a node that removes the node in case something has gone wrong while adding it.
=> Fixed a problem with the focus panel timeline

Net2Plan-GUI/Net2Plan-GUI-Exec/src/main/java/com/net2plan/gui/GUINet2Plan.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/GUINetworkDesign.java
- It is now possible to run key shortcuts such as "Open console: Alt + F12" from the windows at the network design plugin.
- The newly added shortcuts correspond to the ones found on the menu items on the top menu bar.
- Plugin shortcuts have not been added though, to prevent unwanted changes.
=> Added global net2plan controls to the windows at network design.

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_route.java
- Extra add options do not appear anymore for routes when there are no demands in the topology.
=> Solved issue#98

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_route.java
- "View/Edit backup routes" pop-up  menu does work again.
=> Solved issue #99

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/whatIfAnalysisPane/WhatIfAnalysisPane.java
- Added a JScrollPane to the text area.
- Set a JSplitPane to keep a 30/70 proportion between text and the execution panel.
- Simplified the toggle button.
=> Solving issue #105: What-If analysis is not correctly displayed.

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/specificTables/AdvancedJTable_networkElement.java
Bug with tips when expandind and contracting attributes has been fixed
=> Bug with tips when expandind and contracting attributes has been fixed

Net2Plan-Core/src/main/java/com/net2plan/internal/plugins/IGUIModule.java, Net2Plan-GUI/Net2Plan-GUI-Exec/src/main/java/com/net2plan/gui/GUINet2Plan.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/GUINetworkDesign.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/CellRenderers.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/ElementSelection.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/interfaces/IVisualizationCallback.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/onlineSimulationPane/OnlineSimulationPane.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/MoveNodePlugin.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/TopologyPanel.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/ViewEditTopologyTablesPane.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/AdvancedJTable_networkElement.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_demand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_forwardingRule.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_layer.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_link.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_multicastDemand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_multicastTree.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_node.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_resource.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_route.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_srg.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/whatIfAnalysisPane/WhatIfAnalysisPane.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/test/java/com/net2plan/gui/plugins/GUINetworkDesignTest.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/test/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/AdvancedJTable_networkElement_actions_Test.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/test/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_link_actions_Test.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/test/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_node_actions_Test.java, Net2Plan-Launcher/src/main/java/com/net2plan/launcher/GUILauncher.java
- The tables now respond to keyboard commands, both simple and shift movement.
- Solved a problem with GUI Launcher.
- Retouched the GUINetworkDesign so that test do not launch a GUI.
- Reworked some tests.
=> Solved a number of problems

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/GUINetworkDesign.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/focusPane/FocusPane.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/interfaces/ITopologyCanvas.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/jung/JUNGCanvas.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/ViewEditTopologyTablesPane.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/AdvancedJTable_networkElement.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_demand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_forwardingRule.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_layer.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_link.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_multicastDemand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_multicastTree.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_node.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_resource.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_route.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_srg.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/test/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/AdvancedJTable_networkElement_Test.java
- Table rows are now selectable when changing row or column order.
=> Solving issue #111: Unselectable rows.

Net2Plan-Core/src/main/java/com/net2plan/internal/ErrorHandling.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/GUINetworkDesign.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/ViewEditTopologyTablesPane.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/AdvancedJTable_networkElement.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_demand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_forwardingRule.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_layer.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_link.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_multicastDemand.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_multicastTree.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_node.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_resource.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_route.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_srg.java
- Solved a bug in the table update where the row pointers where not correctly synchronize.
=> Solved issue #114: Cannot set a row value when changing order

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/ViewEditTopologyTablesPane.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/AdvancedJTable_networkElement.java
- Corrected the getSelectedElements and SelectItem methods so that the view and model are in synch.
=> Solved row selection when table order was changes

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/focusPane/FocusPane.java
A bug in Focus Panel when updating has been fixed
=> Now, FocusPanel is cleared before updating.

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/FileChooserNetworkDesign.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/TopologyPanel.java
- It is now possible to load designs and traffic matrix from files different to .n2p
=> Recovered lost IO filters.

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/TableSearcher.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/test/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/TableSearcherTest.java, pom.xml
- Optimized how the aggregation cells are calculated.
- Added a tool for GUILauncher to launch N2P in Debug mode.
- Minor bugs.
=> Changing the way the aggregation line is calculated

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/viewEditTopolTables/controlTables/specificTables/AdvancedJTable_link.java
- The link table tried to read routes from a hop by hop layer.
=> Solved a bug where a link tried to routes from a hop layer

Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/jung/JUNGCanvas.java
- Fixed a mistake where JUNG drew the layers in the opposite order as they were provided.
=> Fixed JUNG layer draw order

Net2Plan-GUI/Net2Plan-GUI-Exec/src/main/java/com/net2plan/gui/utils/JNumberField.java, Net2Plan-GUI/Net2Plan-GUI-Plugins/Net2Plan-NetworkDesign/src/main/java/com/net2plan/gui/plugins/networkDesign/topologyPane/LinkStyleSelector.java
Changed JTextField for JNumberField in LinkStyleSelector
=> Using JNumberField in Link Style Selector

Net2Plan-Core/src/main/java/com/net2plan/libraries/OpticalImpairmentUtils.java, Net2Plan-Examples/src/main/java/com/net2plan/examples/general/reports/Report_WDM_lineEngineering.java, Net2Plan-Examples/src/main/java/com/net2plan/examples/general/reports/Report_WDM_lineEngineering_GNModel.java, Net2Plan-Launcher/pom.xml
Added OpticalImpairmentsUtils and Reports
=> Adding OpticalImpairments Utils
